export const buttons = [
  {
    id: '0',
    keyCode: 192,
    titleRu: 'ё',
    titleEn: '`',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '1',
    keyCode: 49,
    titleRu: '1',
    titleEn: '1',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '2',
    titleRu: '2',
    keyCode: 50,
    titleEn: '2',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '3',
    keyCode: 51,
    titleRu: '3',
    titleEn: '3',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '4',
    keyCode: 52,
    titleRu: '4',
    titleEn: '4',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '5',
    keyCode: 53,
    titleRu: '5',
    titleEn: '5',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '6',
    keyCode: 54,
    titleRu: '6',
    titleEn: '6',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '7',
    keyCode: 55,
    titleRu: '7',
    titleEn: '7',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '8',
    keyCode: 56,
    titleRu: '8',
    titleEn: '8',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '9',
    keyCode: 57,
    titleRu: '9',
    titleEn: '9',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '10',
    keyCode: 48,
    titleRu: '0',
    titleEn: '0',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '11',
    keyCode: 189,
    titleRu: '-',
    titleEn: '-',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '12',
    keyCode: 187,
    titleRu: '=',
    titleEn: '=',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '13',
    keyCode: 8,
    titleRu: 'Backspace',
    titleEn: 'Backspace',
    className: 'btn lg dark',
    isLetter: false,
  },
  {
    id: '14',
    keyCode: 9,
    titleRu: 'Tab',
    titleEn: 'Tab',
    className: 'btn sm dark',
    isLetter: false,
  },
  {
    id: '15',
    keyCode: 81,
    titleRu: 'й',
    titleEn: 'q',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '16',
    keyCode: 87,
    titleRu: 'ц',
    titleEn: 'w',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '17',
    keyCode: 69,
    titleRu: 'у',
    titleEn: 'e',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '18',
    keyCode: 82,
    titleRu: 'к',
    titleEn: 'r',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '19',
    keyCode: 84,
    titleRu: 'е',
    titleEn: 't',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '20',
    keyCode: 89,
    titleRu: 'н',
    titleEn: 'y',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '21',
    keyCode: 85,
    titleRu: 'г',
    titleEn: 'u',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '22',
    keyCode: 73,
    titleRu: 'ш',
    titleEn: 'i',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '23',
    keyCode: 79,
    titleRu: 'щ',
    titleEn: 'o',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '24',
    keyCode: 80,
    titleRu: 'з',
    titleEn: 'p',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '25',
    keyCode: 219,
    titleRu: 'х',
    titleEn: '[',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '26',
    keyCode: 221,
    titleRu: 'ъ',
    titleEn: ']',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '27',
    keyCode: 220,
    titleRu: '\\',
    titleEn: '\\',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '28',
    keyCode: 46,
    titleRu: 'Del',
    titleEn: 'Del',
    className: 'btn xsm dark',
    isLetter: false,
  },
  {
    id: '29',
    keyCode: 20,
    titleRu: 'Caps Lock',
    titleEn: 'Caps Lock',
    className: 'btn lg dark',
    isLetter: false,
  },
  {
    id: '30',
    keyCode: 65,
    titleRu: 'ф',
    titleEn: 'a',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '31',
    keyCode: 83,
    titleRu: 'ы',
    titleEn: 's',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '32',
    keyCode: 68,
    titleRu: 'в',
    titleEn: 'd',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '33',
    keyCode: 70,
    titleRu: 'а',
    titleEn: 'f',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '34',
    keyCode: 71,
    titleRu: 'п',
    titleEn: 'g',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '35',
    keyCode: 72,
    titleRu: 'р',
    titleEn: 'h',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '36',
    keyCode: 74,
    titleRu: 'о',
    titleEn: 'j',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '37',
    keyCode: 75,
    titleRu: 'л',
    titleEn: 'k',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '38',
    keyCode: 76,
    titleRu: 'д',
    titleEn: 'l',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '39',
    keyCode: 186,
    titleRu: 'ж',
    titleEn: ';',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '40',
    keyCode: 222,
    titleRu: 'э',
    titleEn: '\'',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '41',
    keyCode: 13,
    titleRu: 'Enter',
    titleEn: 'Enter',
    className: 'btn medium dark',
    isLetter: false,
  },
  {
    id: '42',
    keyCode: 16,
    titleRu: 'Shift',
    titleEn: 'Shift',
    className: 'btn lg dark',
    isLetter: false,
  },
  {
    id: '43',
    keyCode: 90,
    titleRu: 'я',
    titleEn: 'z',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '44',
    keyCode: 88,
    titleRu: 'ч',
    titleEn: 'x',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '45',
    keyCode: 67,
    titleRu: 'с',
    titleEn: 'c',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '46',
    keyCode: 86,
    titleRu: 'м',
    titleEn: 'v',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '47',
    keyCode: 66,
    titleRu: 'и',
    titleEn: 'b',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '48',
    keyCode: 78,
    titleRu: 'т',
    titleEn: 'n',
    className: 'btn',
  },
  {
    id: '49',
    keyCode: 77,
    titleRu: 'ь',
    titleEn: 'm',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '50',
    keyCode: 188,
    titleRu: 'б',
    titleEn: ',',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '51',
    keyCode: 190,
    titleRu: 'ю',
    titleEn: '.',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '52',
    keyCode: 191,
    titleRu: '.',
    titleEn: '/',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '53',
    keyCode: 38,
    titleRu: '&#8593;',
    titleEn: '&#8593;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '54',
    keyCode: 16,
    titleRu: 'Shift',
    titleEn: 'Shift',
    className: 'btn medium dark',
    isLetter: false,
  },
  {
    id: '55',
    keyCode: 17,
    titleRu: 'Ctrl',
    titleEn: 'Ctrl',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '56',
    keyCode: 91,
    titleRu: 'Win',
    titleEn: 'Win',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '57',
    keyCode: 18,
    titleRu: 'Alt',
    titleEn: 'Alt',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '58',
    keyCode: 32,
    titleRu: '',
    titleEn: '',
    className: 'btn xl dark',
    isLetter: false,
  },
  {
    id: '59',
    keyCode: 18,
    titleRu: 'Alt',
    titleEn: 'Alt',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '60',
    keyCode: 37,
    titleRu: '&#8592;',
    titleEn: '&#8592;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '61',
    keyCode: 40,
    titleRu: '&#8595;',
    titleEn: '&#8595;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '62',
    keyCode: 39,
    titleRu: '&#8594;',
    titleEn: '&#8594;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '63',
    keyCode: 17,
    titleRu: 'Ctrl',
    titleEn: 'Ctrl',
    className: 'btn dark',
    isLetter: false,
  },
]