export const buttons = [
  {
    id: '0',
    titleRu: 'ё',
    titleEn: '`',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '1',
    titleRu: '1',
    titleEn: '1',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '2',
    titleRu: '2',
    titleEn: '2',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '3',
    titleRu: '3',
    titleEn: '3',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '4',
    titleRu: '4',
    titleEn: '4',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '5',
    titleRu: '5',
    titleEn: '5',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '6',
    titleRu: '6',
    titleEn: '6',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '7',
    titleRu: '7',
    titleEn: '7',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '8',
    titleRu: '8',
    titleEn: '8',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '9',
    titleRu: '9',
    titleEn: '9',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '10',
    titleRu: '0',
    titleEn: '0',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '11',
    titleRu: '-',
    titleEn: '-',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '12',
    titleRu: '=',
    titleEn: '=',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '13',
    titleRu: 'Backspace',
    titleEn: 'Backspace',
    className: 'btn lg dark',
    isLetter: false,
  },
  {
    id: '14',
    titleRu: 'Tab',
    titleEn: 'Tab',
    className: 'btn sm dark',
    isLetter: false,
  },
  {
    id: '15',
    titleRu: 'й',
    titleEn: 'q',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '16',
    titleRu: 'ц',
    titleEn: 'w',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '17',
    titleRu: 'у',
    titleEn: 'e',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '18',
    titleRu: 'к',
    titleEn: 'r',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '19',
    titleRu: 'е',
    titleEn: 't',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '20',
    titleRu: 'н',
    titleEn: 'y',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '21',
    titleRu: 'г',
    titleEn: 'u',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '22',
    titleRu: 'ш',
    titleEn: 'i',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '23',
    titleRu: 'щ',
    titleEn: 'o',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '24',
    titleRu: 'з',
    titleEn: 'p',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '25',
    titleRu: 'х',
    titleEn: '[',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '26',
    titleRu: 'ъ',
    titleEn: ']',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '27',
    titleRu: '\\',
    titleEn: '\\',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '28',
    titleRu: 'Del',
    titleEn: 'Del',
    className: 'btn xsm dark',
    isLetter: false,
  },
  {
    id: '29',
    titleRu: 'Caps Lock',
    titleEn: 'Caps Lock',
    className: 'btn lg dark',
    isLetter: false,
  },
  {
    id: '30',
    titleRu: 'ф',
    titleEn: 'a',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '31',
    titleRu: 'ы',
    titleEn: 's',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '32',
    titleRu: 'в',
    titleEn: 'd',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '33',
    titleRu: 'а',
    titleEn: 'f',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '34',
    titleRu: 'п',
    titleEn: 'g',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '35',
    titleRu: 'р',
    titleEn: 'h',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '36',
    titleRu: 'о',
    titleEn: 'j',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '37',
    titleRu: 'л',
    titleEn: 'k',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '38',
    titleRu: 'д',
    titleEn: 'l',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '39',
    titleRu: 'ж',
    titleEn: ';',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '40',
    titleRu: 'э',
    titleEn: '\'',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '41',
    titleRu: 'Enter',
    titleEn: 'Enter',
    className: 'btn medium dark',
    isLetter: false,
  },
  {
    id: '42',
    titleRu: 'Shift',
    titleEn: 'Shift',
    className: 'btn lg dark',
    isLetter: false,
  },
  {
    id: '43',
    titleRu: 'я',
    titleEn: 'z',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '44',
    titleRu: 'ч',
    titleEn: 'x',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '45',
    titleRu: 'с',
    titleEn: 'c',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '46',
    titleRu: 'м',
    titleEn: 'v',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '47',
    titleRu: 'и',
    titleEn: 'b',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '48',
    titleRu: 'т',
    titleEn: 'n',
    className: 'btn',
  },
  {
    id: '49',
    titleRu: 'ь',
    titleEn: 'm',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '50',
    titleRu: 'б',
    titleEn: ',',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '51',
    titleRu: 'ю',
    titleEn: '.',
    className: 'btn',
    isLetter: true,
  },
  {
    id: '52',
    titleRu: '.',
    titleEn: '/',
    className: 'btn',
    isLetter: false,
  },
  {
    id: '53',
    titleRu: '&#8593;',
    titleEn: '&#8593;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '54',
    titleRu: 'Shift',
    titleEn: 'Shift',
    className: 'btn medium dark',
    isLetter: false,
  },
  {
    id: '55',
    titleRu: 'Ctrl',
    titleEn: 'Ctrl',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '56',
    titleRu: 'Win',
    titleEn: 'Win',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '57',
    titleRu: 'Alt',
    titleEn: 'Alt',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '58',
    titleRu: '',
    titleEn: '',
    className: 'btn xl dark',
    isLetter: false,
  },
  {
    id: '59',
    titleRu: 'Alt',
    titleEn: 'Alt',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '60',
    titleRu: '&#8592;',
    titleEn: '&#8592;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '61',
    titleRu: '&#8595;',
    titleEn: '&#8595;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '62',
    titleRu: '&#8594;',
    titleEn: '&#8594;',
    className: 'btn dark',
    isLetter: false,
  },
  {
    id: '63',
    titleRu: 'Ctrl',
    titleEn: 'Ctrl',
    className: 'btn dark',
    isLetter: false,
  },
]